=head1 NAME

twepl - The Perl embeddings for HTML.

=head1 SYNOPSYS

twepl B<-[ceux]+> B<-t:?X> B<files...>

=head1 DESCRIPTION

The Perl-Code embeddings for HTML, it is simple and easy.

adding I<E<lt>$ Perl-Code $E<gt>> to your HTML.

=head1 CGI

inserting first line to

  #!/your/path/twepl (options)?

=head1 OPTIONS

B<-[ceux]+>

B<c> = output internal code.
B<e> = example mode, with coloring source.
B<u> = use beta features.I<(template mode only now)>
B<x> = older version compatible, every tags every execute.

B<-t:?X> = set timeout of B<X> seconds.

=head1 SEE ALSO

L<HTML::EmbeddedPerl>

=head1 AUTHOR

TWINKLE COMPUTING <twinkle@cpan.org>

=head1 COPYRIGHT

Copyright (c) 2010 TWINKLE COMPUTING All rights reserved.

=head1 LISENCE

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
