=encoding utf-8

=head1 名前

twepl - (主に)HTMLへのPerlコード埋め込み

=head1 概要

最初の行へ挿入します。

  #!/あなたの/パス/twepl

=head1 説明

(主に)HTMLのためのPerlコード埋め込み、それは簡素で容易です。

I<E<lt>$ Perl-Code $E<gt>> をHTMLへ追加します。
またコードブロックが多数あれば、それらコードブロック間で局所化された変数は使用できません。

=head1 オプション

tweplのためのオプションは何もありません。

=head1 参考

L<HTML::EmbeddedPerl>

=head1 著者

トゥインクル・コンピューティング <twinkle@cpan.org>

=head1 ライセンス

Copyright (c) 2010 Twinkle Computing All rights reserved.

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
